# Github actions CI file
# Ryan Mulhall 2020
# Builds and runs make check in two containers, one with mpi, one without
name: FRE-NCtools CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        with_mpi: ['','--with-mpi']
        enable_quad_precision: ['', '--enable-quad-precision']
    env:
        MPI: ${{ matrix.with_mpi }}
        QUAD_P: ${{ matrix.enable_quad_precision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container
      run: docker build . -t fre-nctools
    - name: Build and run tests
      run: docker run -u root --entrypoint "/bin/sh" --env MPI --env QUAD_P fre-nctools /build.sh
    - name: Save log file on failure
      uses: actions/upload-artifact@v2.2.1
      if: failure()
      with:
          name: test-suite.log
          path: t/test-suite.log
